/**
 * @enum {string}
 */
export const Period = {
    '1M': '1M',
    '1Y': '1Y',
    '2Y': '2Y',
    '3Y': '3Y',
    '4Y': '4Y',
    '5Y': '5Y',
    '6Y': '6Y',
    '7Y': '7Y',
    '8Y': '8Y',
    '9Y': '9Y',
    '10Y': '10Y',
}

/**
 * @enum {string}
 */
export const RenewalMode = {
    'AUTORENEW': 'AUTORENEW',
    'AUTODELETE': 'AUTODELETE',
    'AUTOEXPIRE': 'AUTOEXPIRE',
}

/**
 * @enum {string}
 */
export const TransferMode = {
    'DEFAULT': 'DEFAULT',
    'AUTOAPPROVE': 'AUTOAPPROVE',
    'AUTODENY': 'AUTODENY',
}

/**
 * @enum {string}
 */
export const RecordType = {
    A: 'A',
    AAAA: 'AAAA',
    AFSDB: 'AFSDB',
    ALIAS: 'ALIAS',
    CAA: 'CAA',
    CERT: 'CERT',
    CNAME: 'CNAME',
    HINFO: 'HINFO',
    HTTPS: 'HTTPS',
    IPSECKEY: 'IPSECKEY',
    KEY: 'KEY',
    LOC: 'LOC',
    MX: 'MX',
    NAPTR: 'NAPTR',
    NS: 'NS',
    OPENPGPKEY: 'OPENPGPKEY',
    PTR: 'PTR',
    RP: 'RP',
    SMIMEA: 'SMIMEA',
    SOA: 'SOA',
    SRV: 'SRV',
    SSHFP: 'SSHFP',
    SVCB: 'SVCB',
    TLSA: 'TLSA',
    TXT: 'TXT',
    URI: 'URI',
    URL: 'URL',
}

/**
 * @enum {string}
 */
export const UrlRedirectType = {
    HEADER301: 'HEADER301',
    HEADER302: 'HEADER302',
    FRAME: 'FRAME',
}

/**
 * @enum {string}
 */
export const ContactType = {
    ORG: 'ORG',
    PERSON: 'PERSON',
    ROLE: 'ROLE',
}

/**
 * @link https://www.inwx.com/en/help/apidoc/f/ch03.html#type.country
 * @enum {string}
 */
const Country = {
    CW: 'CW',
    SX: 'SX',
    BQ: 'BQ',
    XK: 'XK',
    AF: 'AF',
    AX: 'AX',
    AL: 'AL',
    DZ: 'DZ',
    AS: 'AS',
    AD: 'AD',
    AO: 'AO',
    AI: 'AI',
    AQ: 'AQ',
    AG: 'AG',
    AR: 'AR',
    AM: 'AM',
    AW: 'AW',
    AC: 'AC',
    AU: 'AU',
    AT: 'AT',
    AZ: 'AZ',
    BS: 'BS',
    BH: 'BH',
    BD: 'BD',
    BB: 'BB',
    BY: 'BY',
    BE: 'BE',
    BZ: 'BZ',
    BJ: 'BJ',
    BM: 'BM',
    BT: 'BT',
    BO: 'BO',
    BA: 'BA',
    BW: 'BW',
    BV: 'BV',
    BR: 'BR',
    IO: 'IO',
    BN: 'BN',
    BG: 'BG',
    BF: 'BF',
    BI: 'BI',
    KH: 'KH',
    CM: 'CM',
    CA: 'CA',
    CV: 'CV',
    KY: 'KY',
    CF: 'CF',
    TD: 'TD',
    CL: 'CL',
    CN: 'CN',
    CX: 'CX',
    CC: 'CC',
    CO: 'CO',
    KM: 'KM',
    CG: 'CG',
    CD: 'CD',
    CK: 'CK',
    CR: 'CR',
    CI: 'CI',
    HR: 'HR',
    CU: 'CU',
    CY: 'CY',
    CZ: 'CZ',
    DK: 'DK',
    DJ: 'DJ',
    DM: 'DM',
    DO: 'DO',
    EC: 'EC',
    EG: 'EG',
    SV: 'SV',
    GQ: 'GQ',
    ER: 'ER',
    EE: 'EE',
    ET: 'ET',
    FK: 'FK',
    FO: 'FO',
    FJ: 'FJ',
    FI: 'FI',
    FR: 'FR',
    GF: 'GF',
    PF: 'PF',
    TF: 'TF',
    GA: 'GA',
    GM: 'GM',
    GE: 'GE',
    DE: 'DE',
    GH: 'GH',
    GI: 'GI',
    GR: 'GR',
    GL: 'GL',
    GD: 'GD',
    GP: 'GP',
    GU: 'GU',
    GT: 'GT',
    GG: 'GG',
    GN: 'GN',
    GW: 'GW',
    GY: 'GY',
    HT: 'HT',
    HM: 'HM',
    VA: 'VA',
    HN: 'HN',
    HK: 'HK',
    HU: 'HU',
    IS: 'IS',
    IN: 'IN',
    ID: 'ID',
    IR: 'IR',
    IQ: 'IQ',
    IE: 'IE',
    IM: 'IM',
    IL: 'IL',
    IT: 'IT',
    JM: 'JM',
    JP: 'JP',
    JE: 'JE',
    JO: 'JO',
    KZ: 'KZ',
    KE: 'KE',
    KI: 'KI',
    KP: 'KP',
    KR: 'KR',
    KW: 'KW',
    KG: 'KG',
    LA: 'LA',
    LV: 'LV',
    LB: 'LB',
    LS: 'LS',
    LR: 'LR',
    LY: 'LY',
    LI: 'LI',
    LT: 'LT',
    LU: 'LU',
    MO: 'MO',
    MK: 'MK',
    MG: 'MG',
    MW: 'MW',
    MY: 'MY',
    MV: 'MV',
    ML: 'ML',
    MT: 'MT',
    MH: 'MH',
    MQ: 'MQ',
    MR: 'MR',
    MU: 'MU',
    YT: 'YT',
    MX: 'MX',
    FM: 'FM',
    MD: 'MD',
    MC: 'MC',
    MN: 'MN',
    ME: 'ME',
    MS: 'MS',
    MA: 'MA',
    MZ: 'MZ',
    MM: 'MM',
    NA: 'NA',
    NR: 'NR',
    NP: 'NP',
    NL: 'NL',
    NC: 'NC',
    NZ: 'NZ',
    NI: 'NI',
    NE: 'NE',
    NG: 'NG',
    NU: 'NU',
    NF: 'NF',
    MP: 'MP',
    NO: 'NO',
    OM: 'OM',
    PK: 'PK',
    PW: 'PW',
    PS: 'PS',
    PA: 'PA',
    PG: 'PG',
    PY: 'PY',
    PE: 'PE',
    PH: 'PH',
    PN: 'PN',
    PL: 'PL',
    PT: 'PT',
    PR: 'PR',
    QA: 'QA',
    RE: 'RE',
    RO: 'RO',
    RU: 'RU',
    RW: 'RW',
    BL: 'BL',
    SH: 'SH',
    KN: 'KN',
    LC: 'LC',
    MF: 'MF',
    PM: 'PM',
    VC: 'VC',
    WS: 'WS',
    SM: 'SM',
    ST: 'ST',
    SA: 'SA',
    SN: 'SN',
    RS: 'RS',
    SC: 'SC',
    SL: 'SL',
    SG: 'SG',
    SK: 'SK',
    SI: 'SI',
    SB: 'SB',
    SO: 'SO',
    ZA: 'ZA',
    GS: 'GS',
    SS: 'SS',
    ES: 'ES',
    LK: 'LK',
    SD: 'SD',
    SR: 'SR',
    SJ: 'SJ',
    SZ: 'SZ',
    SE: 'SE',
    CH: 'CH',
    SY: 'SY',
    TW: 'TW',
    TJ: 'TJ',
    TZ: 'TZ',
    TH: 'TH',
    TL: 'TL',
    TG: 'TG',
    TK: 'TK',
    TO: 'TO',
    TT: 'TT',
    TN: 'TN',
    TR: 'TR',
    TM: 'TM',
    TC: 'TC',
    TV: 'TV',
    UG: 'UG',
    UA: 'UA',
    AE: 'AE',
    GB: 'GB',
    US: 'US',
    UM: 'UM',
    UY: 'UY',
    UZ: 'UZ',
    VU: 'VU',
    VE: 'VE',
    VN: 'VN',
    VG: 'VG',
    VI: 'VI',
    WO: 'WO',
    WF: 'WF',
    EH: 'EH',
    YE: 'YE',
    ZM: 'ZM',
    ZW: 'ZW',
}

/**
 * @typedef {Object} DomainDate
 * @property {string} scalar
 * @property {string} xmlrpc_type
 * @property {number} timestamp
 */

/**
 * @typedef {{
 *   roId: number, 
 *   domain: string, 
 *   "domain-ace": string, 
 *   withPrivacy: string,
 *   period: Period, 
 *   crDate: DomainDate,
 *   exDate: DomainDate,
 *   reDate: DomainDate,
 *   upDate: DomainDate,
 *   transferLock:boolean, 
 *   status:string,
 *   authCode:string,
 *   renewalMode:RenewalMode,
 *   transferMode:TransferMode,
 *   registrant: number,
 *   admin: number,
 *   tech: number,
 *   billing: number,
 *   noDelegation: boolean,
 *   ns: Array<string>,
 *   extData?: Object<string, string>,
 *   tags: Array<string>,
 *   verificationStatus: string,
 * }} Domain
 */

/**
 * @typedef {{
 *   id: number,
 *   name: string,
 *   type: RecordType,
 *   content: string,
 *   ttl: number,
 *   prio: number,
 *   urlRedirectType: UrlRedirectType|undefined,
 *   urlRedirectTitle: string|undefined,
 *   urlRedirectDescription: string|undefined,
 *   urlRedirectKeywords: string|undefined,
 *   urlRedirectFavIcon: string|undefined,
 *   urlAppend: boolean|undefined,
 * }} DomainRecord
 */


/**
 * @typedef {{
*   domain: string, 
*   identifier: string, 
*   import: string, 
*   resource: string
* }} DomainObject
*/

/**
 * @typedef {{
 *   domain: string, 
 *   identifier: string, 
 *   buildImport: (identifier) => string, 
 *   buildResource: (identifier) => string
 * }} RecordResourceGenerator
 */

/**
 * @typedef {{
*   roId: number, 
*   id: number, 
*   type: ContactType, 
*   name: string,
*   org: string, 
*   street: string,
*   city: string,
*   pc: string,
*   sp: string,
*   cc: Country, 
*   voice: string,
*   fax: string,
*   email: string,
*   remarks: string,
*   protection: boolean,
*   usedCount: number,
*   verificationStatus: string,
* }} Contact
*/

/**
 * @typedef {{
 *   identifier: string,
 *   roId: number,
 *   import: string,
 *   resource: string,
 * }} ContactObject
 */